# Pre-commit configuration using ruff as the primary tool
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix]
      # Run the formatter
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict

  # Client TypeScript checks
  - repo: local
    hooks:
      - id: client-typecheck
        name: TypeScript Type Check (Client)
        entry: bash -c 'cd client && npm run typecheck'
        language: system
        files: ^client/.*\.(ts|tsx)$
        pass_filenames: false

      - id: client-lint
        name: ESLint (Client)
        entry: bash -c 'cd client && npm run lint'
        language: system
        files: ^client/.*\.(ts|tsx|js|jsx)$
        pass_filenames: false
