version: "3.9"
services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ENV=dev
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
  worker:
    build: .
    command:
      [
        "celery",
        "-A",
        "storytime.worker.celery_app:celery_app",
        "worker",
        "--loglevel=info",
      ]
    environment:
      - ENV=dev
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    working_dir: /app/src
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storytime
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  pgdata:
