version: "3.9"
services:
  client:
    build:
      context: ./client
      target: development
    ports:
      - "3000:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:8000
    depends_on:
      - api
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    environment:
      - ENV=docker
    volumes:
      - .:/app
      - /app/static  # Preserve the built static files from the image
    depends_on:
      - db
      - redis
    command: [
      "uvicorn",
      "storytime.api.main:app",
      "--reload",
      "--host=0.0.0.0",
      "--port=8000"
    ]
  worker:
    build: .
    command:
      [
        "celery",
        "-A",
        "storytime.worker.celery_app:celery_app",
        "worker",
        "--loglevel=info",
      ]
    env_file:
      - .env.docker
    environment:
      - ENV=docker
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    working_dir: /app/src
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: storytime
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"
volumes:
  pgdata:
