[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "storytime"
version = "0.1.0"
description = "Audiobook parsing and TTS generation toolkit"
authors = [{ name = "Storytime" }]
readme = "README.md"
requires-python = ">=3.11,<4.0"
dependencies = [
    "pydantic>=2.0.0",
    "google-generativeai>=0.3.0",
    "openai>=1.82.0",
    "python-dotenv>=1.0.0",
    "pydub>=0.25.1",
    "requests>=2.31.0",
    "pytest>=7.0.0",
    "fastapi>=0.115.0",
    "uvicorn[standard]>=0.34.0",
    "pydantic[email]",
    "pydantic-settings>=2.0.0",
    "elevenlabs>=2.1.0",
    "python-multipart>=0.0.6",
    "httpx>=0.27.0",
    "numpy>=1.26.0",
    "junjo>=0.45.0",
    "opentelemetry-sdk>=1.33.0",
    "opentelemetry-exporter-otlp>=1.33.0",
    "opentelemetry-exporter-otlp-proto-http>=1.33.0",
    "celery[redis]",
    "psycopg2-binary",
    "asyncpg",
    "sqlalchemy"
]

[project.optional-dependencies]
development = [
    "pytest",
    "black",
    "isort",
    "flake8",
    "mypy",
    "pre-commit",
]

[tool.setuptools.packages.find]
where = ["src"]

[tool.isort]
profile = "black"

[tool.poetry.dependencies]
elevenlabs = ">=2.1.0" 