"""add_tutor_conversation_table

Revision ID: 556295a40b3b
Revises: c181b831cfcc
Create Date: 2025-07-22 21:47:44.373922

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "556295a40b3b"
down_revision: str | None = "c181b831cfcc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tutor_conversations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("job_id", sa.String(), nullable=False),
        sa.Column("session_type", sa.String(), nullable=False),
        sa.Column("is_intro_completed", sa.Integer(), nullable=False),
        sa.Column("messages", sa.JSON(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("session_metadata", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["jobs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_tutor_conv_created", "tutor_conversations", ["created_at"], unique=False)
    op.create_index(
        "idx_tutor_conv_user_job", "tutor_conversations", ["user_id", "job_id"], unique=False
    )
    op.create_index(
        op.f("ix_tutor_conversations_job_id"), "tutor_conversations", ["job_id"], unique=False
    )
    op.create_index(
        op.f("ix_tutor_conversations_user_id"), "tutor_conversations", ["user_id"], unique=False
    )
    op.drop_index(
        op.f("ix_vector_store_files_user_vector_store_id"), table_name="vector_store_files"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_vector_store_files_user_vector_store_id"),
        "vector_store_files",
        ["user_vector_store_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_tutor_conversations_user_id"), table_name="tutor_conversations")
    op.drop_index(op.f("ix_tutor_conversations_job_id"), table_name="tutor_conversations")
    op.drop_index("idx_tutor_conv_user_job", table_name="tutor_conversations")
    op.drop_index("idx_tutor_conv_created", table_name="tutor_conversations")
    op.drop_table("tutor_conversations")
    # ### end Alembic commands ###
