"""Initial schema from current models

Revision ID: d5a58121007b
Revises:
Create Date: 2025-06-21 21:20:28.471025

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d5a58121007b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
