# Kamal deployment configuration for StorytimeTTS

# Main service configuration
service: storytime

# Docker image configuration
image: storytime/app

# Deployment timeouts
deploy_timeout: 120

# Registry for storing images
registry:
  server: registry.digitalocean.com/storytime
  username:
    - KAMAL_REGISTRY_USERNAME
  password:
    - KAMAL_REGISTRY_PASSWORD

# Servers configuration
servers:
  web:
    hosts:
      - 129.212.136.218
  worker:
    hosts:
      - 129.212.136.218
    cmd: celery -A storytime.worker.celery_app:celery_app worker --loglevel=info

# Environment variables
env:
  clear:
    ENV: production
    TTS_PROVIDER: openai
    TTS_MAX_CONCURRENCY: 8
  secret:
    - DATABASE_URL
    - REDIS_URL
    - CELERY_BROKER_URL
    - OPENAI_API_KEY
    - ELEVENLABS_API_KEY
    - ELEVEN_LABS_API_KEY
    - GOOGLE_API_KEY
    - JWT_SECRET_KEY
    - DO_SPACES_KEY
    - DO_SPACES_SECRET
    - DO_SPACES_REGION
    - DO_SPACES_BUCKET
    - DO_SPACES_ENDPOINT
    - POSTGRES_PASSWORD
    - KAMAL_REGISTRY_USERNAME
    - KAMAL_REGISTRY_PASSWORD

# Accessories (external services like databases)
accessories:
  db:
    image: postgres:16
    host: 129.212.136.218
    env:
      clear:
        POSTGRES_USER: postgres
        POSTGRES_DB: storytime
      secret:
        - POSTGRES_PASSWORD
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:7
    host: 129.212.136.218
    port: 6379
    volumes:
      - /var/lib/redis/data:/data


# Kamal proxy configuration
proxy:
  ssl: true
  host: plinytheai.com
  app_port: 8000
  healthcheck:
    path: /up
    interval: 10
    timeout: 10

# Builder configuration
builder:
  arch: amd64

# Hooks for migrations
boot:
  limit: 10% # Deploy to 10% of hosts at a time
  wait: 30 # Wait 30 seconds between deployments
